### ISSUE TITLE
Crash on world load (Tectonic V2.1, Fabric 1.19.2)

### ISSUE THREAD

**Issue by TheRealIceCracker** [Apollounknowndev/tectonic#41]
[Crash report pastebin](https://pastebin.com/haDnrHMm)

Let me know what I can do to help!

**Comment by Apollounknowndev** [comment]
This appears to be due to a mod conflict, although I can't identify exactly *which* mod is causing it. There is a fix, however it will break Terralith compatibility.
Go to `.minecraft/config/tectonic.json`, and set `legacy_mode` to `true`. This will cause the game to not crash on world load, but Terralith biomes won't generate.

**Comment by TheRealIceCracker** [comment]
Alright, I will try to spend some time disabling mods and seeing if I can pin down what's causing it, hopefully by the end of the weekend. Thanks!

**Comment by DavidBlackCN** [comment]
Got the similar issues in the same version.
（Tectonic=V2.1 Fabric=1.19.2）
The error occurred after I updated Tectonic from V1.1.10 to V2.1
The difference is that I am using a server,and different biomes with error.
I have noticed that many of the mods I use are the same as yours, hope you can quickly identify the problems！

logs：
`java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/biome]: [tectonic:alpine_meadow, tectonic:cold_beach, tectonic:cold_plains, tectonic:cold_river, tectonic:coral_river, tectonic:desert_dunes, tectonic:dripstone_river, tectonic:evergreen_forest, tectonic:grasslands, tectonic:icy_river, tectonic:lantern_river, tectonic:lukewarm_beach, tectonic:lukewarm_river, tectonic:lush_river, tectonic:old_growth_evergreen_forest, tectonic:red_desert, tectonic:red_desert_dunes]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:194) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.21.jar:?]
Caused by: java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/biome]: [tectonic:alpine_meadow, tectonic:cold_beach, tectonic:cold_plains, tectonic:cold_river, tectonic:coral_river, tectonic:desert_dunes, tectonic:dripstone_river, tectonic:evergreen_forest, tectonic:grasslands, tectonic:icy_river, tectonic:lantern_river, tectonic:lukewarm_beach, tectonic:lukewarm_river, tectonic:lush_river, tectonic:old_growth_evergreen_forest, tectonic:red_desert, tectonic:red_desert_dunes]
	at net.minecraft.class_2370.method_40276(class_2370.java:347) ~[server-intermediary.jar:?]
	at net.minecraft.class_5455$class_6892.method_40332(class_5455.java:128) ~[server-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.class_5455$class_6891.<init>(class_5455.java:168) ~[server-intermediary.jar:?]
	at net.minecraft.class_5455.method_40316(class_5455.java:324) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43613(Main.java:166) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:24) ~[server-intermediary.jar:?]
	at net.minecraft.class_6904.method_40431(class_6904.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:158) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:952) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:946) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:156) ~[server-intermediary.jar:?]
	... 4 more`

**Comment by Apollounknowndev** [comment]
If you're trying to upgrade a world, you need to open `(server folder)/config/tectonic.json` and set `legacy_mode` to `true`. Once the world can be activated again, `legacy_mode` can be turned off.

**Comment by DeadRedmond** [comment]
I followed the method you suggested, and while the world successfully loaded, I am now encountering a substantial number of error messages similar to the following examples:

-     Recoverable errors when loading section [-7, 18, 21]: (Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/biome]: tectonic:alpine_meadow -> using default)
-     [C2ME worker #1/ERROR]: Recoverable errors when loading section [46, 17, -48]: (Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/biome]: tectonic:cold_river -> using default)

Is there a recommended solution to address these errors and ensure proper functionality?

**Comment by Apollounknowndev** [comment]
Those error messages are just the world removing Tectonic biomes and transitioning to vanilla ones. They only happen once.

**Comment by DeadRedmond** [comment]
> They only happen once.

It looks like these messages appear every time i restart my server.

**Comment by CODwar2005** [comment]
and if the generation itself just doesn't work?
